#!/usr/bin/env python3
""" async function """
import typing
async_generator = __import__('0-async_generator').async_generator


async def async_comprehension() -> typing.List[float]:
    """return 10 random numbers generated by async generator"""
    return [i async for i in async_generator()]
